name: lipsar_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  intl: ^0.17.0-nullsafety.2
  rxdart: ^0.23.1
  flutter_local_notifications: ^3.0.3
  flutter_svg: ^0.19.0
  like_button: ^1.0.4
  async_loader: ^0.1.1
  url_launcher: ^5.7.6
  easy_localization: ^2.3.3+1
  mask_text_input_formatter: ^1.1.0
  rest_data: ^0.3.1
  yoyo_player: ^0.1.0
  youtube_player_flutter: ^7.0.0+7
  json_serializable: ^3.5.0

  firebase_storage: ^7.0.0
  cloud_firestore: ^0.16.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_launcher_name: ^0.0.1


flutter_launcher_name:
  name: "Tronic Show"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  #uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - android/assets/images/logosec.png
    - android/assets/images/1.png
    - android/assets/images/2.png
    - android/assets/images/3.png
    - android/assets/images/4.png
    - android/assets/images/logowhite.png
    - android/assets/translations/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: android/assets/fonts/MyFlutterApp.ttf
    - family: Baloo
      fonts:
        - asset: android/assets/fonts/baloo-cyrillic.ttf
    - family: Montserrat
      fonts:
        - asset: android/assets/fonts/Montserrat-Regular.ttf
        - asset: android/assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: android/assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: android/assets/fonts/Montserrat-Italic.ttf
          style: italic

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
